assetic:
    assets:
        js_vendors:
            inputs: ~
        js_plugins:
            inputs: ~
        js_app:
            inputs:
                - '@DimeReportBundle/Resources/public/js/app/report/*'
